name: Validate OpenAPI specifications

on:
  push:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install
      - name: Validate OpenAPI specifications
        run: npm run validate
